name: ci
on: [push, workflow_dispatch]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test
        if: ${{ env.TEST != 'skip' }}
        run: tests/run_tests.sh
        shell: bash
        env:
          LI_AT_COOKIE: ${{ secrets.LI_AT_COOKIE }}

      - name: Build distribution
        run: python setup.py install_egg_info sdist bdist_wheel

      - name: Deploy to PyPi
#        if: contains(github.ref, 'release') # Tag commit with 'release' to publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
